name: environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib=3.1.1
  - scipy
  - time
  - xarray
  - xarray-simlab
  - fastscape
  - hvplot
  - plotly
  - pandas
  - pywget
  - cartopy
  - obspy
  - pip
  - pip:
    - mplstereonet
